services:
    victoire_query.query_helper:
        class: Victoire\Bundle\QueryBundle\Helper\QueryHelper
        arguments:
            - "@victoire_core.helper.business_entity_helper"
            - "@victoire_core.current_view"
            - "@annotation_reader"
            - "@security.token_storage"
