services:
    victoire_widget_map.builder:
        class: Victoire\Bundle\WidgetMapBundle\Builder\WidgetMapBuilder
        arguments:
            - "@victoire_widget_map.datatransformer.widgetmap_to_array"

    victoire_widget_map.position_builder:
        class: Victoire\Bundle\WidgetMapBundle\Builder\WidgetMapPositionBuilder

    victoire_widget_map.widget_data_warmer:
        class: Victoire\Bundle\WidgetMapBundle\Warmer\WidgetDataWarmer
        arguments:
            - "@annotation_reader"
            - "@victoire_view_reference.redis.driver"
            - ["\Victoire\Bundle\MediaBundle\Entity\Media"]

    victoire_widget_map.manager:
        class: Victoire\Bundle\WidgetMapBundle\Manager\WidgetMapManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@victoire_widget_map.builder"
            - "@victoire_widget_map.helper"

    victoire_widget_map.helper:
        class: Victoire\Bundle\WidgetMapBundle\Helper\WidgetMapHelper

    victoire_widget_map.datatransformer.widgetmap_to_array:
        class: Victoire\Bundle\WidgetMapBundle\DataTransformer\WidgetMapToArrayTransformer
