services:
    victoire_widget_map.builder:
        class: Victoire\Bundle\WidgetMapBundle\Builder\WidgetMapBuilder
        arguments:
            - "@victoire_widget_map.contextual_view_warmer"

    victoire_widget_map.widget_data_warmer:
        class: Victoire\Bundle\WidgetMapBundle\Warmer\WidgetDataWarmer
        arguments:
            - "@victoire_view_reference.repository"
            - "@victoire_widget.widget_helper"

    victoire_widget_map.contextual_view_warmer:
        class: Victoire\Bundle\WidgetMapBundle\Warmer\ContextualViewWarmer

    victoire_widget_map.manager:
        class: Victoire\Bundle\WidgetMapBundle\Manager\WidgetMapManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@victoire_widget_map.builder"