parameters:
    victoire_blog_tag_filters_form_type_class: Victoire\Bundle\BlogBundle\Filter\TagFilter
    victoire_blog_category_filters_form_type_class: Victoire\Bundle\BlogBundle\Filter\CategoryFilter
    victoire_blog_date_filters_form_type_class: Victoire\Bundle\BlogBundle\Filter\DateFilter

services:

    ####################################################################################################################
    # Menu
    ####################################################################################################################
    victoire_blog.blog_menu_listener:
        class: Victoire\Bundle\BlogBundle\Listener\BlogMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.build_menu, method: addGlobal, priority: 90 }

    victoire_blog.article_menu.contextual:
        class: Victoire\Bundle\BlogBundle\Listener\BlogMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.article_menu.contextual, method: addContextual}

    victoire_blog.article_settings_menu.contextual:
        class: Victoire\Bundle\BlogBundle\Listener\ArticleMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.article_menu.contextual, method: addContextual}

    victoire_blog.blog_menu.contextual:
        class: Victoire\Bundle\BlogBundle\Listener\BlogMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.blog_menu.contextual, method: addBlogContextual}

    victoire_blog.article_template_menu.menu_listener.contextual:
        class: Victoire\Bundle\BusinessPageBundle\Listener\BusinessPageMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.article_template_menu.contextual, method: addContextual }

    victoire_blog.blog_page_menu.contextual:
        class: Victoire\Bundle\PageBundle\Listener\PageMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.blog_menu.contextual, method: addContextual}

    ####################################################################################################################
    # Forms
    ####################################################################################################################
    #HIERARCHY TREE type
    victoire_blog.hierarchy_tree_type:
        class: Victoire\Bundle\BlogBundle\Form\HierarchyTreeType
        arguments: [ "@property_accessor" ]
        tags:
            - { name: form.type }
    #CATEGORY
    victoire.form.blog.category:
        class: Victoire\Bundle\BlogBundle\Form\CategoryType
        tags:
            - { name: form.type }
    #HIDDENENTITY
    victoire.form.blog.entity_hidden:
        class: Victoire\Bundle\BlogBundle\Form\Type\EntityHiddenType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    #ARTICLE

    victoire_blog.article.subscriber:
        class: Victoire\Bundle\BlogBundle\Listener\ArticleSubscriber
        arguments:
            - @victoire_page.user_callable
            - %victoire_core.user_class%
        tags:
            - { name: doctrine.event_subscriber, connection: default, priority: -11 }

    victoire_blog.article.form.type:
        class: Victoire\Bundle\BlogBundle\Form\ArticleType
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%victoire_i18n.available_locales%"
            - "@request_stack"
        tags:
            - { name: form.type }
    victoire_blog.article.container.form.type:
        class: Victoire\Bundle\BlogBundle\Form\ArticleTemplateType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    victoire_blog.article_settings.form.type:
        class: Victoire\Bundle\BlogBundle\Form\ArticleSettingsType
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%victoire_i18n.available_locales%"
            - "@request_stack"
        tags:
            - { name: form.type }

    victoire_blog.type.tags:
        class: Victoire\Bundle\BlogBundle\Form\TagsType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    #BLOG
    victoire_blog.blog.form.type:
        parent: "victoire_core.view.form.type"
        class: Victoire\Bundle\BlogBundle\Form\BlogType
        tags:
            - { name: form.type }

    victoire_blog.blog_choose.form.type:
        class: Victoire\Bundle\BlogBundle\Form\ChooseBlogType
        arguments:
            - "%victoire_i18n.available_locales%"
            - '@victoire_blog.blog_repository'
        tags:
            - { name: form.type }
    victoire_blog.locale_choose.form.type:
        class: Victoire\Bundle\BlogBundle\Form\ChooseLocaleType
        arguments:
            - "%victoire_i18n.available_locales%"
        tags:
            - { name: form.type }
    victoire_blog.blog_repository:
        class: Victoire\Bundle\BlogBundle\Repository\BlogRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Victoire\Bundle\BlogBundle\Entity\Blog

    victoire_blog.blog_settings.form.type:
        parent: "victoire_core.view.form.type"
        class: Victoire\Bundle\BlogBundle\Form\BlogSettingsType
        tags:
            - { name: form.type }

    victoire_blog.blog_category.form.type:
        class: Victoire\Bundle\BlogBundle\Form\BlogCategoryType
        tags:
            - { name: form.type }

    #CATEGORY FILTER
    victoire_blog.category_filters.form.type:
        class: %victoire_blog_category_filters_form_type_class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@request="
            - "@translator"
        tags:
            - { name: form.type }
            - { name: victoire_core.filter }

    #TAG FILTER
    victoire_blog.tag_filters.form.type:
        class: %victoire_blog_tag_filters_form_type_class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@request="
        tags:
            - { name: form.type }
            - { name: victoire_core.filter }

    #DATE FILTER
    victoire_blog.date_filters.form.type:
        class: %victoire_blog_date_filters_form_type_class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@request="
        tags:
            - { name: form.type }
            - { name: victoire_core.filter }

    victoire_blog.manager.article:
        class: Victoire\Bundle\BlogBundle\Manager\ArticleManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - @victoire_business_page.business_page_builder
            - @victoire_business_page.transformer.virtual_to_business_page_transformer
            - @victoire_page.page_helper
            - @victoire_view_reference.repository

    #  ==================  Filter listener ================== #
    #
    victoire.widget_filter.form.listener.presetdata:
        class: Victoire\Bundle\BlogBundle\Listener\BlogFilterListener
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
        tags:
            - { name: kernel.event_listener, event: victoire.widget_filter.form.pre_set_data, method: manageExtraFiltersFields, priority: 1 }

    victoire.widget_filter.form.listener.presubmit:
        class: Victoire\Bundle\BlogBundle\Listener\BlogFilterListener
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
        tags:
            - { name: kernel.event_listener, event: victoire.widget_filter.form.pre_submit, method: manageExtraFiltersFields, priority: 1 }

    victoire.widget_filter.blog.set.default.values.form.listener:
        class: Victoire\Bundle\BlogBundle\Listener\ArticleFilterDefaultValuesListener
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: kernel.event_listener, event: victoire.widget_filter.form.date.set_default_value, method: setDefaultDateValue, priority: 1 }

    victoire_blog.manager.blog_reference_builder:
        class: Victoire\Bundle\BlogBundle\Builder\BlogReferenceBuilder
        parent: victoire_view_reference.base_view_reference.builder
        tags:
            - { name: victoire_view_reference.view_reference.builder, view: Victoire\Bundle\BlogBundle\Entity\Blog }

    victoire_blog.articleTemplate:
        class: Victoire\Bundle\BlogBundle\Entity\ArticleTemplate
        tags:
            -  { name: victoire_core.bussinessEntityPagePattern, alias: article }
