liip_imagine:
    cache_prefix: uploads/cache
    driver: gd
    data_loader: filesystem
    #cache: no_cache
    data_root: %kernel.root_dir%/../web
    formats : ['jpg', 'jpeg','png', 'gif', 'bmp']
    filter_sets:
        media_list_thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [210, 150], mode: outbound }
        media_detail_thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [500, 500], mode: outbound }
