parameters:
    victoire_media.media_manager.class: 'Victoire\Bundle\MediaBundle\Helper\MediaManager'
    victoire_media.menu.adaptor.class: 'Victoire\Bundle\MediaBundle\Helper\Menu\MediaMenuAdaptor'
    victoire_media.listener.doctrine.class: 'Victoire\Bundle\MediaBundle\EventListener\DoctrineMediaListener'
    victoire_media.form.type.media.class: 'Victoire\Bundle\MediaBundle\Form\Type\MediaType'
    victoire_media.media_creator_service.class: 'Victoire\Bundle\MediaBundle\Helper\Services\MediaCreatorService'
    victoire_media.menubuilder.class: 'Victoire\Bundle\MediaBundle\Helper\Menu\MenuBuilder'


services:
    liip_imagine.data.loader.stream.profile_photos:
        class: "%liip_imagine.binary.loader.stream.class%"
        arguments:
            - "@liip_imagine"
            - ''
        tags:
            - { name: 'liip_imagine.data.loader', loader: 'victoire_media_thumbloader' }

    victoire_media.media_manager:
        class: "%victoire_media.media_manager.class%"

    victoire_media.menu.adaptor:
        class: "%victoire_media.menu.adaptor.class%"
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            -  { name: 'victoire_media.menu.adaptor' }

    victoire_media.listener.doctrine:
        class: "%victoire_media.listener.doctrine.class%"
        arguments: ["@victoire_media.media_manager"]
        tags:
            - { name: 'doctrine.event_listener', event: 'prePersist' }
            - { name: 'doctrine.event_listener', event: 'preUpdate' }
            - { name: 'doctrine.event_listener', event: 'postPersist' }
            - { name: 'doctrine.event_listener', event: 'postUpdate' }
            - { name: 'doctrine.event_listener', event: 'preRemove' }

    form.type.media:
        class: "%victoire_media.form.type.media.class%"
        arguments:
            - "@victoire_media.media_manager"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    victoire_media.media_creator_service:
        class: "%victoire_media.media_creator_service.class%"
        calls:
            - [ setEntityManager, [ "@doctrine.orm.entity_manager" ] ]

    victoire_media.menubuilder:
        class: "%victoire_media.menubuilder.class%"
        arguments: ["@translator", "@service_container"]

    victoire_media.menu.twig.extension:
        class: Victoire\Bundle\MediaBundle\Twig\MenuTwigExtension
        arguments: ["@victoire_media.menubuilder"]
        tags:
            -  { name: 'twig.extension' }

    victoire_core.media_menu_listener:
        class: Victoire\Bundle\MediaBundle\EventListener\MediaMenuListener
        arguments:
            - "@victoire_core.admin_menu_builder"
        tags:
            - { name: kernel.event_listener, event: victoire_core.build_menu, method: addGlobal, priority: 60 }
