services:
    form.type.seo.page:
        class: "Victoire\Bundle\SeoBundle\Form\PageSeoType"
        tags:
            - { name: form.type }
    victoire_seo.helper.pageseo_helper:
        class: Victoire\Bundle\SeoBundle\Helper\PageSeoHelper
        arguments:
            - "@victoire_core.helper.business_entity_helper"
            - "@victoire_business_entity.converter.parameter_converter"
