parameters:
    victoire_business_entity.annotation_driver_class:  Victoire\Bundle\BusinessEntityBundle\Annotation\AnnotationDriver
    victoire_business_entity.business_entity_subscriber_class: Victoire\Bundle\BusinessEntityBundle\EventSubscriber\BusinessEntitySubscriber
    victoire_business_entity.business_entity_type_extension_class: Victoire\Bundle\BusinessEntityBundle\Form\Extension\BusinessEntityTypeExtension
    victoire_business_entity.converter.parameter_converter_class: Victoire\Bundle\BusinessEntityBundle\Converter\ParameterConverter
    victoire_business_entity.cache_reader_class: Victoire\Bundle\BusinessEntityBundle\Reader\BusinessEntityCacheReader
    victoire_business_entity.metadata_listener_class: Victoire\Bundle\BusinessEntityBundle\Listener\MetadataListener
    victoire_business_entity.metadata_builder_class: Victoire\Bundle\BusinessEntityBundle\Doctrine\MetadataBuilder

services:

    victoire_business_entity.converter.parameter_converter:
        class: "%victoire_business_entity.converter.parameter_converter_class%"

    victoire_business_entity.business_entity_subscriber:
        class: "%victoire_business_entity.business_entity_subscriber_class%"
        arguments:
            - @victoire_business_page.business_page_builder
            - @victoire_core.helper.business_entity_helper
            - @victoire_business_page.business_page_helper
            - @event_dispatcher
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    victoire_business_entity.business_entity_type_extension:
        class: "%victoire_business_entity.business_entity_type_extension_class%"
        arguments:
            - "@victoire_core.helper.business_entity_helper"
        tags:
            - { name: form.type_extension }


#  ==================  Provider ================== #

    victoire_business_entity.provider.entity_proxy_provider:
        class: Victoire\Bundle\BusinessEntityBundle\Provider\EntityProxyProvider

    ####################################################################################################################
    # Security voter
    ####################################################################################################################
    victoire_business_entity.security.voter.business_entity_owner_voter:
        class: Victoire\Bundle\BusinessEntityBundle\Security\Voter\BusinessEntityOwnerVoter
        arguments:
            - '%victoire_core.user_class%'
        tags:
            - { name: security.voter }

    victoire_core.entity.business_entity_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Victoire\Bundle\BusinessEntityBundle\Entity\BusinessEntity

    victoire_core.entity.business_property_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Victoire\Bundle\BusinessEntityBundle\Entity\BusinessProperty

    victoire_business_entity.resolver.business_entity_resolver:
        class: Victoire\Bundle\BusinessEntityBundle\Resolver\BusinessEntityResolver

    victoire_business_entity.annotation_driver:
        class: "%victoire_business_entity.annotation_driver_class%"
        arguments:
            - "@annotation_reader"
            - "@event_dispatcher"
            - "@victoire_widget.widget_helper"
            - "%victoire_core.base_paths%"
            
    victoire_business_entity.warmer:
        class: Victoire\Bundle\BusinessEntityBundle\CacheWarmer\BusinessEntityWarmer
        arguments:
            - "@victoire_business_entity.annotation_driver"
        tags:
            - { name: kernel.cache_warmer}
    victoire_business_entity.cache_reader:
        class: "%victoire_business_entity.cache_reader_class%"
        arguments:
            - "@victoire_core.cache"
            - "@victoire_widget.widget_helper"
            - "@victoire_business_entity.annotation_driver"
