services:
    victoire_widget.widget_content_resolver:
        class: Victoire\Bundle\WidgetBundle\Resolver\WidgetContentResolver
        arguments:
            - @victoire_widget.widget_content_resolver_chain

    victoire_widget.base_widget_content_resolver:
        class: Victoire\Bundle\WidgetBundle\Resolver\BaseWidgetContentResolver
        calls:
            - [setQueryHelper, ["@victoire_query.query_helper"]]
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]

    victoire_widget.widget_helper:
        class: Victoire\Bundle\WidgetBundle\Helper\WidgetHelper
        arguments: [@service_container]

    victoire_widget.widget_form_builder:
        class: Victoire\Bundle\WidgetBundle\Builder\WidgetFormBuilder
        arguments: [@service_container]

    victoire_widget.widget_renderer:
        class: Victoire\Bundle\WidgetBundle\Renderer\WidgetRenderer
        arguments:
            - @service_container
            - @victoire_widget.widget_cache
            - @victoire_widget.widget_helper
            - @victoire_core.victoire_collector

    victoire_widget.widget_cache:
        class: Victoire\Bundle\WidgetBundle\Cache\WidgetCache
        arguments:
            - @snc_redis.victoire_client
            - @security.authorization_checker
            - @victoire_widget.widget_helper

    victoire_widget.widget_manager:
        class: Victoire\Bundle\WidgetBundle\Model\WidgetManager
        arguments:
            - @victoire_widget.widget_helper
            - @victoire_widget.widget_form_builder
            - @victoire_widget.widget_content_resolver
            - @victoire_widget.widget_renderer
            - @doctrine.orm.entity_manager
            - @victoire_form.error_helper
            - @request
            - @victoire_widget_map.manager
            - @victoire_widget_map.builder
            - @victoire_business_entity.cache_reader
            - @templating
            - @victoire_page.page_helper
            - %victoire_core.slots%
            - @victoire_business_page.transformer.virtual_to_business_page_transformer
        scope: request

    widget_manager:
        alias: victoire_widget.widget_manager

    victoire_widget.widget_content_resolver_chain:
        class: Victoire\Bundle\WidgetBundle\Resolver\Chain\WidgetContentResolverChain
        arguments:
            - @victoire_widget.widget_helper

    victoire_widget.widget_item_content_resolver_chain:
        class: Victoire\Bundle\WidgetBundle\Resolver\Chain\WidgetItemChain

    victoire_widget.twig.link_extension:
        class: Victoire\Bundle\WidgetBundle\Twig\LinkExtension
        arguments:
            - @router
            - @request_stack
            - %victoire_seo.analytics%
            - @victoire_core.helper.business_entity_helper
            - @victoire_business_page.business_page_helper
            - @victoire_page.page_helper
            - @doctrine.orm.entity_manager
            - @logger
            - @victoire.repository.error_page
            - %victoire_core.businessTemplates%
        tags:
            - { name: twig.extension }

    victoire_widget.widget_style_type:
        class: Victoire\Bundle\WidgetBundle\Form\WidgetStyleType
        arguments:
            - @kernel
            - @file_locator
        tags:
            - { name: form.type }

    victoire_widget.cache.widget_cache_clearer:
        class: Victoire\Bundle\WidgetBundle\Cache\WidgetCacheClearer
        arguments:
            - @victoire_widget.widget_cache
        tags:
            - { name: kernel.cache_clearer }

    victoire_widget.resolver.widget_resolver:
        class: Victoire\Bundle\WidgetBundle\Resolver\WidgetResolver
        arguments:
            - "@=service('victoire_criteria.chain.data_source_chain')"
            - "@security.authorization_checker"
