imports:
    - { resource: security.yml }

knp_menu:
    twig:
        template: VictoireCoreBundle:Menu:knp_menu_main.html.twig

# Stof Configuration
stof_doctrine_extensions:
    default_locale: fr
    translation_fallback: false
    # class:
    #     sluggable: Victoire\Bundle\CoreBundle\Listener\SluggableListener
    orm:
        default:
          tree: true
          sluggable: true

victoire_core:
    widgets: ~
    slots:
        default_menu_bar:
            max: 1
            widgets:
                menu: ~
        default_mini_sidebar:
            widgets:
                filter: ~
                text: ~
        default_full:
            max: 10
            widgets:
                text: ~
                label: ~
                image: ~
                list: ~
                archive: ~
                file: ~
        default_social_sidebar:
            widgets:
                text: ~
                redactor: ~
                label: ~
                image: ~
                list: ~
                archive: ~

av_alertify:
    contexts:
        victoire:
            engine: "codrops-notification"
            translationDomain: "victoire"
