services:
#  ==================  Widgets ================== #
    victoire_core.entity_proxy.fields_builder:
        class: Victoire\Bundle\CoreBundle\Form\Builder\EntityProxyFieldsBuilder
        arguments:
            - @victoire_business_entity.cache_reader
            - @translator

    victoire_core.widget_subscriber:
        class: Victoire\Bundle\CoreBundle\EventSubscriber\WidgetSubscriber
        arguments:
            - @victoire_core.view_css_builder
            - @victoire_widget_map.builder
        tags:
            - { name: doctrine.event_subscriber, connection: default }

#  ==================  MENU ================== #
    victoire_core.admin_menu_builder:
        class: Victoire\Bundle\CoreBundle\Menu\MenuBuilder
        arguments: [ '@knp_menu.factory', '@security.context' ]

    victoire_core.admin_menu:
        class: Knp\Menu\MenuItem
        factory_service: victoire_core.admin_menu_builder
        factory_method: getMenu
        scope: request
        tags:
            - { name: knp_menu.menu, alias: admin_menu }

    victoire_core.admin_menu.navbar_top:
        class: Knp\Menu\MenuItem
        factory_service: victoire_core.admin_menu_builder
        factory_method: getTopNavbar
        scope: request
        tags:
            - { name: knp_menu.menu, alias: topnavbar }

    victoire_core.admin_menu.navbar_left:
        class: Knp\Menu\MenuItem
        factory_service: victoire_core.admin_menu_builder
        factory_method: getLeftNavbar
        scope: request
        tags:
            - { name: knp_menu.menu, alias: leftnavbar }

    victoire_core.menu_dispatcher:
        class: Victoire\Bundle\CoreBundle\Listener\MenuDispatcher
        arguments:
            - "@event_dispatcher"
            - "@security.context"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    victoire_core.backend_menu_listener:
        class: Victoire\Bundle\CoreBundle\Listener\BackendMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.backend_menu.global, method: addGlobal, priority: 100 }

    victoire_core.listener.controller_listener:
        class: Victoire\Bundle\CoreBundle\Listener\ControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: preExecuteAutorun }

#  ==================  Template ================== #
    victoire_core.template_mapper:
        class: Victoire\Bundle\CoreBundle\Template\TemplateMapper
        arguments: ["@service_container"]

    victoire_templating:
        alias: victoire_core.template_mapper

#  ==================  Twig ================== #
    victoire_core.twig.cms_extension:
        class: Victoire\Bundle\CoreBundle\Twig\Extension\CmsExtension
        arguments:
            - "@Victoire_widget.widget_renderer"
            - "@victoire_templating"
            - "@security.context"
            - "@victoire_core.widget_exception_handler"
            - "@victoire_core.current_view"
            - "@victoire_core.view_cache_helper"
            - "@twig"
        tags:
            - { name: twig.extension }

    victoire_core.twig.globals_extension:
        class: Victoire\Bundle\CoreBundle\Twig\Extension\GlobalsExtension
        arguments:
            - "@victoire_templating"
            - "@session"
        tags:
            - { name: twig.extension }

#  ==================  Cache ================== #

    victoire_core.cache:
        class: Victoire\Bundle\CoreBundle\Cache\VictoireCache
        arguments:
            - "%kernel.debug%"
            - "%victoire_core.cache_dir%"

    victoire_core.view_cache_helper:
        class: Victoire\Bundle\CoreBundle\Helper\ViewCacheHelper
        arguments:
            - "%kernel.cache_dir%"
            - "@victoire_view_reference.helper"

    victoire_core.cache_builder:
        class: Victoire\Bundle\CoreBundle\Cache\Builder\CacheBuilder
        arguments:
            - "@victoire_core.cache"

#  ==================  Subscribers ================== #

    victoire_core.widget_discriminator_map.subscriber:
        class: Victoire\Bundle\CoreBundle\EventSubscriber\WidgetDiscriminatorMapSubscriber
        calls:
            - [ setWidgets, ["%victoire_core.widgets%"] ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    victoire_core.entity_proxy.subscriber:
        class: Victoire\Bundle\CoreBundle\EventSubscriber\EntityProxySubscriber
        calls:
            - [ setBusinessEntityCacheReader, ["@victoire_business_entity.cache_reader"] ]
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata, priority: 10}

    victoire_core.cache_subscriber:
        class: Victoire\Bundle\CoreBundle\EventSubscriber\CacheSubscriber
        arguments:
            - "@victoire_core.cache_builder"
        tags:
            - { name: kernel.event_subscriber }


#  ==================  Cache =================== #
    victoire_core.cache_warmer.entity_proxy_warmer:
        class: Victoire\Bundle\CoreBundle\CacheWarmer\EntityProxyWarmer
        arguments:
            - "@victoire_core.helper.business_entity_helper"
            - "@file_locator"
        tags:
            - { name: kernel.cache_warmer, priority: 100} #Must be lower than victoire_business_entity.warmer

    victoire_core.cache_warmer.view_warmer:
        class: Victoire\Bundle\CoreBundle\CacheWarmer\ViewCacheWarmer
        arguments:
            - @victoire_core.view_helper
            - @victoire_core.view_cache_helper
            - @doctrine.orm.entity_manager
        tags:
        - { name: kernel.event_listener, event: kernel.request, method: warmUp }

    victoire_core.entity_proxy.cache_driver:
        class: Victoire\Bundle\CoreBundle\CacheWarmer\EntityProxyCacheDriver
        arguments:
            - "@annotation_reader"
            - "%kernel.cache_dir%"

    victoire_core.helper.business_entity_helper:
        class: Victoire\Bundle\BusinessEntityBundle\Helper\BusinessEntityHelper
        arguments:
            - "@victoire_business_entity.cache_reader"
            - "@victoire_core.cache_builder"

    victoire_core.helper.queriable_business_entity_helper:
        class: Victoire\Bundle\BusinessEntityBundle\Helper\BusinessEntityHelper
        parent: victoire_core.helper.business_entity_helper
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]

#  ==================  Error handler =================== #

    victoire_core.widget_exception_handler:
        class: Victoire\Bundle\CoreBundle\Handler\WidgetExceptionHandler
        arguments:
            - "@security.context"
            - "@twig"
            - "%kernel.debug%"
            - "@victoire_templating"

#  ==================  View ================== #


    victoire_core.view_helper:
        class: Victoire\Bundle\CoreBundle\Helper\ViewHelper
        arguments:
            - "@victoire_business_entity.converter.parameter_converter"
            - "@victoire_core.helper.business_entity_helper"
            - "@doctrine.orm.entity_manager"
            - "@victoire_view_reference.builder"
            - "@victoire_view_reference.helper"
            - "@victoire_view_reference.provider"

    victoire_core.view_css_builder:
        class: Victoire\Bundle\CoreBundle\Builder\ViewCssBuilder
        arguments:
            - @victoire_widget.widget_renderer
            - '%kernel.root_dir%'

    victoire_core.view_css_listener:
        class: Victoire\Bundle\CoreBundle\Listener\ViewCssListener
        arguments:
            - @victoire_core.view_css_builder
            - @doctrine.orm.entity_manager
            - @victoire_widget_map.builder
        tags:
            - { name: kernel.event_listener, event: victoire.on_render_page, method: onRenderPage }

    victoire_core.current_view:
        class: Victoire\Bundle\CoreBundle\Helper\CurrentViewHelper


    twig.extension.routing:
        class: 'Victoire\Bundle\CoreBundle\Twig\Extension\RoutingExtention'
        public: false
        arguments:
            - '@victoire_page.page_helper'
            - '@router'

    victoire_core.routing_loader:
        class: Victoire\Bundle\CoreBundle\Route\RouteLoader
        arguments:
            - '%victoire_core.widgets%'
        tags:
            - { name: routing.loader }

    victoire_core.url_builder:
        class: Victoire\Bundle\CoreBundle\Helper\UrlBuilder