services:
#  ==================  Widgets ================== #
    victoire_core.entity_proxy.fields_builder:
        class: Victoire\Bundle\CoreBundle\Form\Builder\EntityProxyFieldsBuilder
        arguments:
            - "@victoire_core.entity.business_property_repository"
            - "@victoire_business_entity.cache_reader"
            - "%victoire_core.widgets%"
            - "@translator"

    victoire_core.widget_subscriber:
        class: Victoire\Bundle\CoreBundle\EventSubscriber\WidgetSubscriber
        arguments:
            - @victoire_core.view_css_builder
            - @victoire_widget_map.builder
        tags:
            - { name: doctrine.event_subscriber, connection: default }

#  ==================  MENU ================== #
    victoire_core.admin_menu_builder:
        class: Victoire\Bundle\CoreBundle\Menu\MenuBuilder
        arguments: [ '@knp_menu.factory', '@security.authorization_checker' ]

    victoire_core.admin_menu:
        class: Knp\Menu\MenuItem
        factory_service: victoire_core.admin_menu_builder
        factory_method: getMenu
        scope: request
        tags:
            - { name: knp_menu.menu, alias: admin_menu }

    victoire_core.admin_menu.navbar_top:
        class: Knp\Menu\MenuItem
        factory_service: victoire_core.admin_menu_builder
        factory_method: getTopNavbar
        scope: request
        tags:
            - { name: knp_menu.menu, alias: topnavbar }

    victoire_core.admin_menu.navbar_left:
        class: Knp\Menu\MenuItem
        factory_service: victoire_core.admin_menu_builder
        factory_method: getLeftNavbar
        scope: request
        tags:
            - { name: knp_menu.menu, alias: leftnavbar }

    victoire_core.menu_dispatcher:
        class: Victoire\Bundle\CoreBundle\Listener\MenuDispatcher
        arguments:
            - "@event_dispatcher"
            - "@security.token_storage"
            - "@security.authorization_checker"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    victoire_core.backend_menu_listener:
        class: Victoire\Bundle\CoreBundle\Listener\BackendMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.backend_menu.global, method: addGlobal, priority: 100 }

    victoire_core.listener.controller_listener:
        class: Victoire\Bundle\CoreBundle\Listener\ControllerListener
        arguments:
            - "@event_dispatcher"
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: preExecuteAutorun }

#  ==================  Twig ================== #
    victoire_core.twig.cms_extension:
        class: Victoire\Bundle\CoreBundle\Twig\Extension\CmsExtension
        arguments:
            - "@Victoire_widget.widget_renderer"
            - "@security.authorization_checker"
            - "@victoire_core.widget_exception_handler"
            - "@victoire_core.current_view"
            - "@victoire_view_reference.repository"
            - "@twig"
            - "@victoire_widget.resolver.widget_resolver"
        tags:
            - { name: twig.extension }

    victoire_core.twig.globals_extension:
        class: Victoire\Bundle\CoreBundle\Twig\Extension\GlobalsExtension
        arguments:
            - "@session"
        tags:
            - { name: twig.extension }

#  ==================  Cache ================== #

    victoire_core.cache:
        class: Victoire\Bundle\CoreBundle\Cache\VictoireCache
        arguments:
            - "%victoire_core.business_entity_debug%"
            - "%victoire_core.cache_dir%"

    victoire_core.cache_builder:
        class: Victoire\Bundle\CoreBundle\Cache\Builder\CacheBuilder
        arguments:
            - "@victoire_core.cache"

#  ==================  Subscribers ================== #

    victoire_core.widget_discriminator_map.subscriber:
        class: Victoire\Bundle\CoreBundle\EventSubscriber\WidgetDiscriminatorMapSubscriber
        calls:
            - [ setWidgets, ["%victoire_core.widgets%"] ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }


    victoire_core.cache_subscriber:
        class: Victoire\Bundle\CoreBundle\EventSubscriber\CacheSubscriber
        arguments:
            - "@victoire_core.cache_builder"
        tags:
            - { name: kernel.event_subscriber }


#  ==================  Cache =================== #b

    victoire_core.helper.business_entity_helper:
        class: Victoire\Bundle\BusinessEntityBundle\Helper\BusinessEntityHelper
        arguments:
            - "@victoire_core.entity.orm_business_entity_repository"
        lazy: true

#  ==================  Error handler =================== #

    victoire_core.widget_exception_handler:
        class: Victoire\Bundle\CoreBundle\Handler\WidgetExceptionHandler
        arguments:
            - "@security.authorization_checker"
            - "%kernel.debug%"
            - @service_container

#  ==================  View ================== #


    victoire_core.view_helper:
        class: Victoire\Bundle\CoreBundle\Helper\ViewHelper
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@victoire_view_reference.provider"
            - "@victoire_view_reference.helper"

    victoire_core.view_css_builder:
        class: Victoire\Bundle\CoreBundle\Builder\ViewCssBuilder
        arguments:
            - @service_container
            - %victoire_twig.responsive%
            - '%kernel.root_dir%'

    victoire_core.view_css_listener:
        class: Victoire\Bundle\CoreBundle\Listener\ViewCssListener
        arguments:
            - @victoire_core.view_css_builder
            - @doctrine.orm.entity_manager
            - @victoire_widget_map.builder
        tags:
            - { name: kernel.event_listener, event: victoire.on_render_page, method: onRenderPage }

    victoire_core.current_view:
        class: Victoire\Bundle\CoreBundle\Helper\CurrentViewHelper


    twig.extension.routing:
        class: 'Victoire\Bundle\CoreBundle\Twig\Extension\RoutingExtention'
        public: false
        arguments:
            - '@victoire_page.page_helper'
            - '@router'
            - '@victoire_i18n.locale_resolver'
            - '@request_stack'
            - '@logger'
            - '@victoire.repository.error_page'
            - '%locale%'

    victoire_core.routing_loader:
        class: Victoire\Bundle\CoreBundle\Route\RouteLoader
        arguments:
            - '%victoire_core.widgets%'
        tags:
            - { name: routing.loader }

    victoire_core.url_builder:
        class: Victoire\Bundle\CoreBundle\Helper\UrlBuilder

    victoire_core.victoire_collector:
        class: Victoire\Bundle\CoreBundle\DataCollector\VictoireCollector
        tags:
            - { name: data_collector, template: 'VictoireCoreBundle:Profiler:widget_cache', id: 'victoire_core.victoire_collector', priority: 200 }

    #  ==================  Repositories ================== #
    victoire.repository.error_page:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Victoire\Bundle\TwigBundle\Entity\ErrorPage

    victoire_core.view.form.type:
        abstract: true
        class: Victoire\Bundle\CoreBundle\Form\ViewType
        arguments:
            - "%victoire_i18n.available_locales%"
            - "@request_stack"
            - "@security.authorization_checker"
